### ISSUE TITLE
南寧的數據可以換成這兩份TSV

### ISSUE THREAD

**Issue by leimaau** [osfans/MCPDict#1]
你好，關於南寧的數據，我開了[新的倉庫](https://github.com/leimaau/Nanning-Dialect-Manual)存放TSV文件，這樣你這邊prepare原本使用的rime碼表就可以換掉，應該可以精簡一些代碼量，而且rime碼表本身不適合直接轉換。另有一個小建議，「南部平話」可以改爲「桂南平話」，後者這個概念比較常見，「南寧白話」標籤可簡化爲「南寧」，大地名與小地名「南寧亭子」排列會整齊些。這個應用很好用，希望有所幫助。

**Comment by osfans** [comment]
@leimaau 已更換，感謝！
