### ISSUE TITLE
請求收錄寧波、鎮海、北侖、定海、岱山字表

### ISSUE THREAD

**Issue by shinzoqchiuq** [osfans/MCPDict#2]
希望音典可以收錄 [甬江話字表](https://github.com/ionkaon/dictionary/) 倉庫下 [`各地字表`](https://github.com/ionkaon/dictionary/tree/master/各地字表) 目錄內的以下 5 份字表。

- [`甬城（考證）.tsv`](https://github.com/ionkaon/dictionary/tree/master/各地字表/甬城（考證）.tsv)（經本人考訂過的寧波城區字音）
- [`鎮海.tsv`](https://github.com/ionkaon/dictionary/tree/master/各地字表/鎮海.tsv)
- [`北侖.tsv`](https://github.com/ionkaon/dictionary/tree/master/各地字表/北侖.tsv)
- [`定海.tsv`](https://github.com/ionkaon/dictionary/tree/master/各地字表/定海.tsv)（舟山城區）
- [`岱山.tsv`](https://github.com/ionkaon/dictionary/tree/master/各地字表/岱山.tsv)

這幾個字表由本人維護，具體信息可以參看該目錄下的 [`README`](https://github.com/ionkaon/dictionary/tree/master/各地字表/README.md) 文件。所有字表均以吳拼注音，拼音方案說明請見 [音系與拼音方案](https://github.com/ionkaon/dictionary/音系與拼音方案.md)。在 [`script`](https://github.com/ionkaon/dictionary/tree/master/script) 目錄下，提供了將各地吳拼轉爲 IPA 的 Python 腳本。

寧波城區字表的字音整理自以下資料：

- 湯珍珠、陳忠敏、吳新賢：《寧波方言詞典》，江蘇教育出版社，1997
- 宁波市地方志编纂委员会：《宁波市志·方言》，中华书局，1995
- 朱彰年、薛恭穆、周志锋、汪维辉：《阿拉宁波话(修订版)》，宁波出版社，2016
- 朱彰年、薛恭穆、周志锋、汪维辉：《宁波方言词典》，汉语大辞典出版社，1996
- 周志锋：《江苏教育版<宁波方言词典>词目用字问题》，方言 2008 年第一期
- 《鄞縣通志·文獻志·方言》，鄞縣通志館，1951
- P. G. von Möllendorff：《The Ningpo Syllabary》，Shanghai: American Presbyterian Mission Press，1901

寧波城區字表中一些字音和寫法經過個人考訂，同時也收錄了大量上述資料未收的字音。

鎮海字表整理自：

- 《镇海县志》编纂委员会：《镇海县志·方言》，中国大百科全书出版社上海分社，1994

北侖字表整理自：

- 周志锋、胡方：《北仑方言》，中国文史出版社，2007

舟山城區字表整理自：

- 方松熹：《舟山方言研究》，社会科学文献出版社，1993

岱山字表整理自：

- 岱山县志编纂委员会：《岱山县志·方言》，浙江人民出版社，2006

倉庫爲 CC BY 4.0 協議，所有字表都可以自由使用。

**Comment by osfans** [comment]
已收錄，感謝！
