### ISSUE TITLE
南寧的資料可以更新了

### ISSUE THREAD

**Issue by leimaau** [osfans/MCPDict#36]
你好，音典中的南寧白話和南寧亭子平話的資料有些陳舊了，新的版本已經更新：https://github.com/leimaau/Nanning-Dialect-Manual

新版本解決了之前所有未解決的問題，參考文獻更多、更完善，且主體部分全部電子化，方調表用字隨時可以查閱、查證：https://github.com/leimaau/bookCollection

南寧白話最主要的參考資料爲：1994年謝建猷《南寧白話同音字彙》、1997年楊煥典《南寧話音檔》、1998年廣西地方誌編纂委員會《廣西通誌·漢語方言誌》、 2007年謝建猷《廣西漢語方言研究》、2008年林亦《廣西南寧白話研究》、2009年陳海倫、林亦《粵語平話土話方音字彙》、邢公畹《漢台語比較手冊》、覃鳳餘、林亦《壯語地名的語言與文化》、語保工程。

南寧亭子平話最主要的參考資料爲：1998年廣西地方誌編纂委員會《廣西通誌·漢語方言誌》、2000年李連進《平話音韻研究》、2009年陳海倫、林亦《粵語平話土話方音字彙》、1997年覃遠雄等《南寧平話詞典》、2006年余瑾《廣西平話研究》、邢公畹《漢台語比較手冊》、覃鳳餘、林亦《壯語地名的語言與文化》、語保工程。

其中字表中的5級字是爲了輸入法設置，大部分爲異體字、俗字和待考字，變動的可能性較大，刪除開去也沒問題，這樣可以省一些空間，當然，如果不嫌佔空間的話，收錄也是可以的，因爲這次更新我已經精簡和重整過這些字了。文件名也改了，「單字音表」改爲「單字讀音表」，避免與文獻的單字音表混淆。

**Comment by osfans** [comment]
d783e1c7856a3c7b8eb978e8aa4910e4e5f9369a
